<?php
// Simple language loader for public site (excludes admin). Uses cookie 'lang' (tr|en).
if (session_status() === PHP_SESSION_NONE) session_start();

// Guard: do nothing for admin area
if (!defined('IN_ADMIN')) {
    // Determine requested language
    $supportedLanguages = ['tr', 'en'];
    $requestedLang = null;

    if (isset($_GET['lang'])) {
        $candidate = strtolower(trim($_GET['lang']));
        if (in_array($candidate, $supportedLanguages, true)) {
            $requestedLang = $candidate;
            setcookie('lang', $requestedLang, time() + (86400 * 365), '/');
            $_COOKIE['lang'] = $requestedLang; // reflect immediately
            // Redirect to same page without lang param to keep clean URLs
            $currentUrl = strtok((isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '/'), '?');
            $query = $_GET;
            unset($query['lang']);
            $redirectUrl = $currentUrl . (empty($query) ? '' : ('?' . http_build_query($query)));
            if (!headers_sent()) {
                header('Location: ' . $redirectUrl);
                exit;
            }
        }
    }

    // Active language
    $langCode = isset($_COOKIE['lang']) && in_array($_COOKIE['lang'], $supportedLanguages, true)
        ? $_COOKIE['lang']
        : 'tr';

    // Translations
    $translations = [
        'tr' => [
            'nav.home' => 'Ana Sayfa',
            'nav.about' => 'Hakkımızda',
            'nav.club' => 'Kulüp Hakkında',
            'nav.teams' => 'Takımlar',
            'nav.gallery' => 'Galeri',
            'nav.announcements_jobs' => 'İlanlar & Duyurular',
            'nav.announcements' => 'Duyurular',
            'nav.jobs' => 'İlanlar',
            'jobs.tab.internship' => 'Staj İlanları',
            'jobs.tab.scholarship' => 'Burs İlanları',
            'jobs.tab.individual' => 'Bireysel İlanlar',
            'jobs.empty.internship' => 'Şu anda staj ilanı bulunmamaktadır. Yakında yeni ilanlar eklenecektir.',
            'jobs.empty.scholarship' => 'Şu anda burs ilanı bulunmamaktadır. Yakında yeni ilanlar eklenecektir.',
            'jobs.empty.individual' => 'Şu anda bireysel ilan bulunmamaktadır. Yakında yeni ilanlar eklenecektir.',
            'nav.events' => 'Etkinlikler',
            'nav.blog' => 'Blog',
            'nav.contact' => 'İletişim',
            'auth.profile' => 'Profilim',
            'auth.logout' => 'Çıkış Yap',
            'auth.login' => 'Giriş Yap',
            'auth.register' => 'Kayıt Ol',
            'nav.more' => 'Daha Fazla',
            'nav.more_info' => 'Daha Fazla Bilgi',
            'lang.label' => 'TR',
            // Index page
            'home.hero.title' => 'Geleceğin Teknolojisini Şekillendiriyoruz',
            'home.hero.desc' => 'ASEC Kulübü ile projeler geliştirin, etkinliklere katılın ve kariyer yolculuğunuzda ilerleyin!',
            'home.hero.cta.join' => 'Hemen Katıl',
            'home.hero.cta.more' => 'Daha Fazla Bilgi',
            'home.hero.cta.notifications' => 'Önemli Bilgilendirmeler',
            'home.features.title' => 'Neler Sunuyoruz?',
            'home.features.project.title' => 'Proje Geliştirme',
            'home.features.project.desc' => 'Proje Komisyonumuz ile fikirlerinizi hayata geçirin. Projenizin başlangıcından tamamlanmasına kadar tüm süreçlerde rehberlik sağlıyor, yenilikçi ve sürdürülebilir projeler geliştirmenize destek oluyoruz.',
            'home.features.events.title' => 'Mesleki Etkinlikler',
            'home.features.events.desc' => 'Etkinlik Departmanımız ile sektörden uzmanlarla düzenlenen konferanslar, seminerler ve bilgilendirme etkinlikleri sayesinde yazılım ve inovasyon alanındaki en güncel gelişmeleri takip edin.',
            'home.features.career.title' => 'Kariyer Fırsatları',
            'home.features.career.desc' => 'Staj, İş ve Burs Departmanımız aracılığıyla güncel staj olanakları, iş ilanları ve burs fırsatlarına erişin. CV hazırlama desteği ve kariyer rehberliği ile sektöre daha donanımlı adım atın.',
            'home.upcoming.title' => 'Yaklaşan Etkinlikler',
            'home.upcoming.details' => 'Detaylar',
            'home.upcoming.none' => 'Şu anda yaklaşan etkinlik bulunmamaktadır.',
            'home.upcoming.view_all' => 'Tüm Etkinlikleri Gör',
            // Footer
            'footer.links.home' => 'Ana Sayfa',
            'footer.links.about' => 'Hakkımızda',
            'footer.links.teams' => 'Takımlar',
            'footer.links.gallery' => 'Galeri',
            'footer.links.announcements' => 'Duyurular',
            'footer.links.events' => 'Etkinlikler',
            'footer.links.blog' => 'Blog',
            'footer.contact' => 'İletişim',
            'footer.social' => 'Sosyal Medya',
            'footer.follow' => 'Bizi takip et, etkinliklerimizden ve projelerimizden haberdar ol.',
            'footer.copy' => 'ASEC Kulübü. Tüm hakları saklıdır.',
            'footer.scroll_top' => 'Yukarı Çık',
            'footer.tagline' => 'Bilim, teknoloji ve topluluk ruhunu bir araya getiriyoruz. <br> Yazılım alanında öğrencilerin gelişimine katkıda bulunuyoruz.',
            // About page
            'about.title' => 'Hakkımızda',
            'about.intro' => 'ASEC Kulübü, Ankara Yıldırım Beyazıt Üniversitesi Yazılım Mühendisliği öğrencileri tarafından kurulan, proje geliştirme, etkinlik organizasyonu, kariyer fırsatları ve uluslararası deneyimler sunarak üyelerinin mesleki gelişimini destekleyen bir topluluktur.',
            'about.description' => 'Ankara Yıldırım Beyazıt Üniversitesi Yazılım Mühendisliği Kulübü (ASEC), 7 aktif departmanı ve 50+ üyesiyle öğrencilerin mesleki gelişimlerini destekleyen, proje geliştirme, etkinlik organizasyonu, staj ve iş fırsatları, yurtdışı deneyimleri, teknik geziler ve sponsorluk çalışmaları yürüten dinamik bir öğrenci toplululuğudur.',
            'about.stats.departments' => 'Aktif Departman',
            'about.stats.members' => 'Üye',
            'about.stats.projects' => 'Proje',
            'about.vision_mission.title' => 'Vizyonumuz & Misyonumuz',
            'about.vision.title' => 'Vizyonumuz',
            'about.vision.description' => 'Teknoloji dünyasında öncü, yenilikçi ve etik değerlere bağlı bireyler yetiştirerek, üyelerimizin mesleki gelişimlerini desteklemek ve sektöre daha donanımlı bireyler olarak adım atmalarını sağlamak.',
            'about.mission.title' => 'Misyonumuz',
            'about.mission.description' => 'Öğrencilere proje geliştirme, etkinlik organizasyonu, staj ve iş fırsatları, yurtdışı deneyimleri, teknik geziler ve sektör bağlantıları sunarak, mezun olmadan önce gerçek dünya deneyimi kazanmalarını sağlamak.',
            // Gallery
            'gallery.title' => 'Galeri',
            'gallery.subtitle' => 'ASEC Kulübü etkinliklerinden kareler ve özel anlar',
            'gallery.filter.all' => 'Tümü',
            'gallery.filter.events' => 'Etkinlikler',
            'gallery.filter.workshops' => 'Atölyeler',
            'gallery.filter.teams' => 'Takım Çalışmaları',
            // Teams
            'teams.page.title' => 'Departmanlarımız',
            'teams.page.subtitle' => 'ASEC Kulübü bünyesinde faaliyet gösteren uzman departmanlarımız',
            'teams.stat.active' => 'Aktif Departman',
            'teams.stat.members' => 'Üye',
            'teams.stat.projects' => 'Proje',
            'teams.role.lead' => 'Departman Başkanı',
            // Board of Directors
            'board.title' => 'Yönetim Kurulu',
            'board.subtitle' => 'ASEC Kulübü yönetim kurulu üyeleri ile tanışın',
            'board.empty.title' => 'Henüz Yönetim Kurulu Üyesi Yok',
            'board.empty.message' => 'Yönetim kurulu üyeleri yakında eklenecektir.',
            // Auth
            'login.title' => 'Giriş Yap',
            'login.individual' => 'Bireysel Giriş',
            'login.corporate' => 'Kurumsal Giriş',
            'login.email' => 'E-posta:',
            'login.password' => 'Şifre:',
            'login.forgot' => 'Şifrenizi mi unuttunuz?',
            'login.reset' => 'Şifremi Sıfırla',
            'login.submit' => 'Giriş Yap',
            'login.no_account' => 'Hesabınız yok mu?',
            'login.register' => 'Üye Ol',
            'login.individual_switch' => 'Bireysel kullanıcı mısınız?',
            'login.individual_link' => 'Bireysel Giriş',
            'register.title' => 'Üye Ol',
            'register.name' => 'İsim Soyisim:',
            'register.phone' => 'Telefon:',
            'register.email' => 'E-posta:',
            'register.university' => 'Üniversite:',
            'register.department' => 'Bölüm:',
            'register.class' => 'Sınıf:',
            'register.password' => 'Şifre:',
            'register.password2' => 'Şifre (Tekrar):',
            'register.requirements.title' => 'Şifreniz en az:',
            'register.requirements.length' => '8 karakter uzunluğunda',
            'register.requirements.upper' => 'Bir büyük harf',
            'register.requirements.lower' => 'Bir küçük harf',
            'register.requirements.number' => 'Bir rakam',
            'register.requirements.special' => 'Bir özel karakter içermelidir',
            'register.submit' => 'Üye Ol',
            'register.have_account' => 'Zaten üye misiniz?',
            'register.login' => 'Giriş Yap',
            'register.success' => 'Kayıt başarılı! Giriş yapabilirsiniz.',
            'register.individual' => 'Bireysel Kayıt',
            'register.corporate' => 'Kurumsal Kayıt',
            'register.corporate.success' => 'Kayıt isteğiniz başarıyla oluşturuldu! Hesabınız yönetici onayından sonra aktif olacaktır.',
            'register.corporate.company_name' => 'Şirket Adı',
            'register.corporate.contact_person' => 'İletişim Kişisi',
            'register.corporate.phone' => 'Telefon',
            'register.corporate.email' => 'E-posta',
            'register.corporate.address' => 'Adres',
            'register.corporate.tax_number' => 'Vergi Numarası',
            'register.corporate.password' => 'Şifre',
            'register.corporate.password2' => 'Şifre Tekrar',
            'register.corporate.requirements.title' => 'Şifre Gereksinimleri:',
            'register.corporate.requirements.length' => 'En az 8 karakter',
            'register.corporate.requirements.upper' => 'En az bir büyük harf',
            'register.corporate.requirements.lower' => 'En az bir küçük harf',
            'register.corporate.requirements.number' => 'En az bir rakam',
            'register.corporate.requirements.special' => 'En az bir özel karakter',
            'register.corporate.submit' => 'Kayıt Ol',
            'register.corporate.have_account' => 'Zaten hesabınız var mı?',
            'register.corporate.login' => 'Giriş Yap',
            // Profile
            'profile.title' => 'Profilim',
            'profile.edit' => 'Profili Düzenle',
            'profile.save' => 'Kaydet',
            'profile.labels.phone' => 'Telefon',
            'profile.labels.university' => 'Üniversite',
            'profile.labels.department' => 'Bölüm',
            'profile.labels.class' => 'Sınıf',
            'profile.labels.birthdate' => 'Doğum Tarihi',
            'profile.labels.address' => 'Adres',
            'profile.labels.bio' => 'Kısa Biyografi',
            'profile.labels.instagram' => 'Sosyal Medya (Instagram)',
            'profile.labels.linkedin' => 'Sosyal Medya (LinkedIn)',
            'profile.labels.achievements' => 'Başarılar',
            'profile.value.not_set' => '(Eklenmedi)',
            'profile.cv.view' => 'CV Görüntüle',
            'profile.cv.add' => 'CV Ekle',
            // Events list
            'events.page.title' => 'Etkinliklerimiz',
            'events.upcoming.title' => 'Yaklaşan Etkinlikler',
            'events.past.title' => 'Geçmiş Etkinlikler',
            'events.detail' => 'Detay',
            'events.quick_detail' => 'Hızlı Detay',
            'events.register' => 'Kayıt Ol',
            'events.loading' => 'Yükleniyor...',
            'events.load_error' => 'Etkinlik detayları yüklenirken bir hata oluştu.',
            // Event detail
            'event.status.upcoming' => 'Yaklaşan Etkinlik',
            'event.status.past' => 'Geçmiş Etkinlik',
            'event.info.date' => 'Tarih',
            'event.info.time' => 'Saat',
            'event.info.place' => 'Yer',
            'event.description' => 'Etkinlik Açıklaması',
            'event.register' => 'Etkinliğe Kayıt Ol',
            'event.gallery' => 'Fotoğraf Galerisi',
            'event.no_photos' => 'Henüz fotoğraf eklenmemiş.',
            'event.back' => 'Tüm Etkinliklere Dön',
            // Contact
            'contact.title' => 'İletişim',
            'contact.info' => 'İletişim Bilgileri',
            'contact.social.title' => 'Sosyal Medyada Biz',
            'contact.whatsapp.title' => 'WhatsApp Grubumuza Katıl!',
            'contact.whatsapp.desc' => 'Kulüp duyuruları, etkinlikler ve iletişim için topluluğumuza hemen katıl!',
            'contact.whatsapp.join' => 'Gruba Hemen Katıl',
            'contact.form.title' => 'Bize Ulaşın',
            'contact.form.success' => 'Mesajınız başarıyla gönderildi!',
            'contact.form.error' => 'Lütfen tüm alanları doldurun.',
            'contact.form.name' => 'Adınız:',
            'contact.form.email' => 'E-posta:',
            'contact.form.subject' => 'Konu:',
            'contact.form.message' => 'Mesajınız:',
            'contact.form.send' => 'Gönder',
            // Blog
            'blog.title' => 'Blog',
            'blog.page.title' => 'Blog Yazılarımız',
            'blog.category.general' => 'Genel',
            'blog.read_more' => 'Devamını Oku',
            'blog.empty.title' => 'Henüz Blog Yazısı Bulunmuyor',
            'blog.empty.desc' => 'Yakında yeni blog yazıları eklenecektir. Lütfen daha sonra tekrar ziyaret edin.',
            'blog.back' => 'Blog Yazılarına Dön',
            // CV
            'cv.page.title' => 'CV Bilgileri',
            'cv.name' => 'Ad Soyad',
            'cv.major' => 'Bölüm / Alan',
            'cv.programming_languages' => 'Programlama Dilleri',
            'cv.software_fields' => 'Yazılım Alanları',
            'cv.worked_companies' => 'Çalıştığı Şirketler',
            'cv.pdf' => 'CV (PDF)',
            'cv.pdf_note' => 'PDF görüntüleyici tarayıcınıza bağlı olarak değişebilir.',
            'cv.edit' => 'CV Düzenle',
            'cv.view_profile' => 'Profili Gör',
            'cv.upload.title' => 'CV Bilgileri',
            'cv.form.major.label' => 'Bölüm / Alan (mezun olunan / okunan):',
            'cv.form.major.placeholder' => 'Örn: Bilgisayar Mühendisliği',
            'cv.form.languages.label' => 'Programlama Dilleri:',
            'cv.form.fields.label' => 'Yazılım Alanları:',
            'cv.form.companies.label' => 'Çalıştığınız Şirketler:',
            'cv.form.companies.note' => 'Şirket geçmişinizi eklemek için satır ekleyin (opsiyonel).',
            'cv.form.companies.placeholder' => 'Örn: ABC Teknoloji A.Ş.',
            'cv.form.add_row' => 'Satır Ekle',
            'cv.form.upload.label' => 'CV Yükle (PDF):',
            'cv.form.upload.current' => 'Yüklü CV:',
            'cv.form.upload.view' => 'Görüntüle',
            'cv.form.save' => 'Kaydet',
            'cv.save.success' => 'Bilgiler başarıyla kaydedildi.',
            'cv.error.only_pdf' => 'Lütfen yalnızca PDF dosyası yükleyin.',
            'cv.error.upload_failed' => 'CV dosyası yüklenemedi.',
            'cv.error.upload_error' => 'CV dosyası yüklenirken bir hata oluştu.',
            'cv.delete' => 'CV Sil',
            'cv.delete.confirm' => 'CV\'nizi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
            'cv.delete.success' => 'CV başarıyla silindi.',
            'cv.delete.error' => 'CV silinirken bir hata oluştu.',
            // Announcements
            'announcements.page.title' => 'Duyurular',
            'announcements.read_more' => 'Detayları Gör',
            'announcements.category.important' => 'Önemli',
            'announcements.category.workshop' => 'Workshop',
            'announcements.category.event' => 'Etkinlik',
            'announcements.month.jan' => 'Oca',
            'announcements.month.feb' => 'Şub',
            'announcements.month.mar' => 'Mar',
            'announcements.month.apr' => 'Nis',
            'announcements.month.may' => 'May',
            'announcements.month.jun' => 'Haz',
            'announcements.month.jul' => 'Tem',
            'announcements.month.aug' => 'Ağu',
            'announcements.month.sep' => 'Eyl',
            'announcements.month.oct' => 'Eki',
            'announcements.month.nov' => 'Kas',
            'announcements.month.dec' => 'Ara',
        ],
        'en' => [
            'nav.home' => 'Home',
            'nav.about' => 'About',
            'nav.club' => 'About the Club',
            'nav.teams' => 'Teams',
            'nav.gallery' => 'Gallery',
            'nav.announcements_jobs' => 'Notices & Announcements',
            'nav.announcements' => 'Announcements',
            'nav.jobs' => 'Notices',
            'jobs.tab.internship' => 'Internship Notices',
            'jobs.tab.scholarship' => 'Scholarship Notices',
            'jobs.tab.individual' => 'Individual Notices',
            'jobs.empty.internship' => 'There are currently no internship notices. New notices will be added soon.',
            'jobs.empty.scholarship' => 'There are currently no scholarship notices. New notices will be added soon.',
            'jobs.empty.individual' => 'There are currently no individual notices. New notices will be added soon.',
            'nav.events' => 'Events',
            'nav.blog' => 'Blog',
            'nav.contact' => 'Contact',
            'auth.profile' => 'My Profile',
            'auth.logout' => 'Log Out',
            'auth.login' => 'Log In',
            'auth.register' => 'Sign Up',
            'nav.more' => 'More',
            'nav.more_info' => 'Learn More',
            'lang.label' => 'EN',
            // Index page
            'home.hero.title' => 'We Shape the Technology of the Future',
            'home.hero.desc' => 'Build projects with ASEC, join events, and advance your career journey!',
            'home.hero.cta.join' => 'Join Now',
            'home.hero.cta.more' => 'Learn More',
            'home.hero.cta.notifications' => 'Important Notifications',
            'home.features.title' => 'What Do We Offer?',
            'home.features.project.title' => 'Project Development',
            'home.features.project.desc' => 'Bring your ideas to life with our Project Commission. We guide you through all stages from start to finish, helping you build innovative and sustainable projects.',
            'home.features.events.title' => 'Professional Events',
            'home.features.events.desc' => 'Keep up with the latest trends in software and innovation through conferences, seminars, and info sessions organized with industry experts.',
            'home.features.career.title' => 'Career Opportunities',
            'home.features.career.desc' => 'Access current internship, job, and scholarship opportunities. Get support for CV preparation and career guidance to step into the industry better equipped.',
            'home.upcoming.title' => 'Upcoming Events',
            'home.upcoming.details' => 'Details',
            'home.upcoming.none' => 'There are no upcoming events at the moment.',
            'home.upcoming.view_all' => 'View All Events',
            // Footer
            'footer.links.home' => 'Home',
            'footer.links.about' => 'About',
            'footer.links.teams' => 'Teams',
            'footer.links.gallery' => 'Gallery',
            'footer.links.announcements' => 'Announcements',
            'footer.links.events' => 'Events',
            'footer.links.blog' => 'Blog',
            'footer.contact' => 'Contact',
            'footer.social' => 'Social Media',
            'footer.follow' => 'Follow us to keep up with our events and projects.',
            'footer.copy' => 'ASEC Club. All rights reserved.',
            'footer.scroll_top' => 'Scroll to Top',
            'footer.tagline' => 'We bring together science, technology and community spirit. <br> We contribute to students\' development in software.',
            // About page
            'about.title' => 'About Us',
            'about.intro' => 'ASEC Club is a community established by Ankara Yıldırım Beyazıt University Software Engineering students, supporting members\' professional development through project development, event organization, career opportunities, and international experiences.',
            'about.description' => 'Ankara Yıldırım Beyazıt University Software Engineering Club (ASEC) is a dynamic student community with 7 active departments and 50+ members, supporting students\' professional development through project development, event organization, internship and job opportunities, international experiences, technical trips, and sponsorship activities.',
            'about.stats.departments' => 'Active Departments',
            'about.stats.members' => 'Members',
            'about.stats.projects' => 'Projects',
            'about.vision_mission.title' => 'Our Vision & Mission',
            'about.vision.title' => 'Our Vision',
            'about.vision.description' => 'To support our members\' professional development and enable them to step into the industry as well-equipped individuals by nurturing pioneering, innovative, and ethically committed individuals in the technology world.',
            'about.mission.title' => 'Our Mission',
            'about.mission.description' => 'To enable students to gain real-world experience before graduation by providing them with project development, event organization, internship and job opportunities, international experiences, technical trips, and industry connections.',
            // Gallery
            'gallery.title' => 'Gallery',
            'gallery.subtitle' => 'Highlights and moments from ASEC events',
            'gallery.filter.all' => 'All',
            'gallery.filter.events' => 'Events',
            'gallery.filter.workshops' => 'Workshops',
            'gallery.filter.teams' => 'Team Work',
            // Teams
            'teams.page.title' => 'Our Departments',
            'teams.page.subtitle' => 'Expert departments operating within ASEC Club',
            'teams.stat.active' => 'Active Departments',
            'teams.stat.members' => 'Members',
            'teams.stat.projects' => 'Projects',
            'teams.role.lead' => 'Department Lead',
            // Board of Directors
            'board.title' => 'Board of Directors',
            'board.subtitle' => 'Meet the ASEC Club board of directors members',
            'board.empty.title' => 'No Board Members Yet',
            'board.empty.message' => 'Board members will be added soon.',
            // Auth
            'login.title' => 'Log In',
            'login.individual' => 'Individual Login',
            'login.corporate' => 'Corporate Login',
            'login.email' => 'Email:',
            'login.password' => 'Password:',
            'login.forgot' => 'Forgot your password?',
            'login.reset' => 'Reset Password',
            'login.submit' => 'Log In',
            'login.no_account' => 'Don\'t have an account?',
            'login.register' => 'Sign Up',
            'login.individual_switch' => 'Are you an individual user?',
            'login.individual_link' => 'Individual Login',
            'register.title' => 'Sign Up',
            'register.name' => 'Full Name:',
            'register.phone' => 'Phone:',
            'register.email' => 'Email:',
            'register.university' => 'University:',
            'register.department' => 'Department:',
            'register.class' => 'Class:',
            'register.password' => 'Password:',
            'register.password2' => 'Password (Repeat):',
            'register.requirements.title' => 'Your password should include at least:',
            'register.requirements.length' => '8 characters',
            'register.requirements.upper' => 'One uppercase letter',
            'register.requirements.lower' => 'One lowercase letter',
            'register.requirements.number' => 'One number',
            'register.requirements.special' => 'One special character',
            'register.submit' => 'Sign Up',
            'register.have_account' => 'Already have an account?',
            'register.login' => 'Log In',
            'register.success' => 'Registration successful! You can log in now.',
            'register.individual' => 'Individual Registration',
            'register.corporate' => 'Corporate Registration',
            'register.corporate.success' => 'Your registration request has been successfully created! Your account will be activated after admin approval.',
            'register.corporate.company_name' => 'Company Name',
            'register.corporate.contact_person' => 'Contact Person',
            'register.corporate.phone' => 'Phone',
            'register.corporate.email' => 'Email',
            'register.corporate.address' => 'Address',
            'register.corporate.tax_number' => 'Tax Number',
            'register.corporate.password' => 'Password',
            'register.corporate.password2' => 'Password (Repeat)',
            'register.corporate.requirements.title' => 'Password Requirements:',
            'register.corporate.requirements.length' => 'At least 8 characters',
            'register.corporate.requirements.upper' => 'At least one uppercase letter',
            'register.corporate.requirements.lower' => 'At least one lowercase letter',
            'register.corporate.requirements.number' => 'At least one number',
            'register.corporate.requirements.special' => 'At least one special character',
            'register.corporate.submit' => 'Sign Up',
            'register.corporate.have_account' => 'Already have an account?',
            'register.corporate.login' => 'Log In',
            // Profile
            'profile.title' => 'My Profile',
            'profile.edit' => 'Edit Profile',
            'profile.save' => 'Save',
            'profile.labels.phone' => 'Phone',
            'profile.labels.university' => 'University',
            'profile.labels.department' => 'Department',
            'profile.labels.class' => 'Class',
            'profile.labels.birthdate' => 'Birth Date',
            'profile.labels.address' => 'Address',
            'profile.labels.bio' => 'Short Bio',
            'profile.labels.instagram' => 'Social Media (Instagram)',
            'profile.labels.linkedin' => 'Social Media (LinkedIn)',
            'profile.labels.achievements' => 'Achievements',
            'profile.value.not_set' => '(Not provided)',
            'profile.cv.view' => 'View CV',
            'profile.cv.add' => 'Upload CV',
            // Events list
            'events.page.title' => 'Our Events',
            'events.upcoming.title' => 'Upcoming Events',
            'events.past.title' => 'Past Events',
            'events.detail' => 'Detail',
            'events.quick_detail' => 'Quick Detail',
            'events.register' => 'Register',
            'events.loading' => 'Loading...',
            'events.load_error' => 'An error occurred while loading event details.',
            // Event detail
            'event.status.upcoming' => 'Upcoming Event',
            'event.status.past' => 'Past Event',
            'event.info.date' => 'Date',
            'event.info.time' => 'Time',
            'event.info.place' => 'Place',
            'event.description' => 'Event Description',
            'event.register' => 'Register for the Event',
            'event.gallery' => 'Photo Gallery',
            'event.no_photos' => 'No photos have been added yet.',
            'event.back' => 'Back to All Events',
            // Contact
            'contact.title' => 'Contact',
            'contact.info' => 'Contact Information',
            'contact.social.title' => 'Find Us on Social Media',
            'contact.whatsapp.title' => 'Join Our WhatsApp Group!',
            'contact.whatsapp.desc' => 'Join our community to receive club announcements and event updates!',
            'contact.whatsapp.join' => 'Join the Group',
            'contact.form.title' => 'Get in Touch',
            'contact.form.success' => 'Your message has been sent successfully!',
            'contact.form.error' => 'Please fill in all fields.',
            'contact.form.name' => 'Your Name:',
            'contact.form.email' => 'Email:',
            'contact.form.subject' => 'Subject:',
            'contact.form.message' => 'Your Message:',
            'contact.form.send' => 'Send',
            // Blog
            'blog.title' => 'Blog',
            'blog.page.title' => 'Our Blog Posts',
            'blog.category.general' => 'General',
            'blog.read_more' => 'Read More',
            'blog.empty.title' => 'No Blog Posts Yet',
            'blog.empty.desc' => 'New blog posts will be added soon. Please check back later.',
            'blog.back' => 'Back to Blog Posts',
            // CV
            'cv.page.title' => 'CV Information',
            'cv.name' => 'Full Name',
            'cv.major' => 'Department / Field',
            'cv.programming_languages' => 'Programming Languages',
            'cv.software_fields' => 'Software Fields',
            'cv.worked_companies' => 'Companies Worked For',
            'cv.pdf' => 'CV (PDF)',
            'cv.pdf_note' => 'The PDF viewer may vary depending on your browser.',
            'cv.edit' => 'Edit CV',
            'cv.view_profile' => 'View Profile',
            'cv.upload.title' => 'CV Information',
            'cv.form.major.label' => 'Department / Field (graduated / studying):',
            'cv.form.major.placeholder' => 'e.g., Computer Engineering',
            'cv.form.languages.label' => 'Programming Languages:',
            'cv.form.fields.label' => 'Software Fields:',
            'cv.form.companies.label' => 'Companies You Worked For:',
            'cv.form.companies.note' => 'Add a row to include your company history (optional).',
            'cv.form.companies.placeholder' => 'e.g., ABC Technology Inc.',
            'cv.form.add_row' => 'Add Row',
            'cv.form.upload.label' => 'Upload CV (PDF):',
            'cv.form.upload.current' => 'Uploaded CV:',
            'cv.form.upload.view' => 'View',
            'cv.form.save' => 'Save',
            'cv.save.success' => 'Information saved successfully.',
            'cv.error.only_pdf' => 'Please upload PDF files only.',
            'cv.error.upload_failed' => 'CV file could not be uploaded.',
            'cv.error.upload_error' => 'An error occurred while uploading the CV file.',
            'cv.delete' => 'Delete CV',
            'cv.delete.confirm' => 'Are you sure you want to delete your CV? This action cannot be undone.',
            'cv.delete.success' => 'CV deleted successfully.',
            'cv.delete.error' => 'An error occurred while deleting the CV.',
            // Announcements
            'announcements.page.title' => 'Announcements',
            'announcements.read_more' => 'View Details',
            'announcements.category.important' => 'Important',
            'announcements.category.workshop' => 'Workshop',
            'announcements.category.event' => 'Event',
            'announcements.month.jan' => 'Jan',
            'announcements.month.feb' => 'Feb',
            'announcements.month.mar' => 'Mar',
            'announcements.month.apr' => 'Apr',
            'announcements.month.may' => 'May',
            'announcements.month.jun' => 'Jun',
            'announcements.month.jul' => 'Jul',
            'announcements.month.aug' => 'Aug',
            'announcements.month.sep' => 'Sep',
            'announcements.month.oct' => 'Oct',
            'announcements.month.nov' => 'Nov',
            'announcements.month.dec' => 'Dec',
        ],
    ];

    /**
     * Translate key to active language string.
     */
    function __t(string $key, ?string $fallback = null): string {
        global $translations, $langCode;
        if (isset($translations[$langCode][$key])) {
            return $translations[$langCode][$key];
        }
        if ($fallback !== null) return $fallback;
        // Fallback to Turkish if exists
        if (isset($translations['tr'][$key])) return $translations['tr'][$key];
        return $key;
    }
}
?>


